# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6839c1ad1922d81a0442dd88df731670aec32b6b5547f595b27d614453ee915d9fd061b60b7b22fd5e86f8cd6423b315b2d32fe50a94af213bcac41df853a610

test:
  secret_key_base: bbd889ecb87725604ab7f843f163f16edba5dd367da705a00cecf5f94da43721119521b95aee0d4598a7d36c26d8f37ef08b048872ce0dd0421090fa0cdba63c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
